name: blue_printer_a
description: A Flutter plugin for connecting to thermal printer via bluetooth
version: 1.0.0
#homepage: https://kakzaki.dev
#repository: https://github.com/kakzaki/blue_thermal_printer
#issue_tracker: https://github.com/kakzaki/blue_thermal_printer/issues
#documentation: https://github.com/kakzaki/blue_thermal_printer/blob/master/README.md

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: id.uttom41.blue_printer_a
        pluginClass: BlueThermalPrinterPlugin
#      ios:
#        pluginClass: BlueThermalPrinterPlugin
#      macos:
#        pluginClass: BlueThermalPrinterPlugin
